### ISSUE TITLE
fix: DB의 news, content 테이블의 excerpt 컬럼의 길이를 수정한다.  

### ISSUE THREAD

**Issue by seokjin8678** [galaxyhub-korea/galaxyhub-backend#26]
## 이슈 내용
https://robertsspaceindustries.com/comm-link/engineering/19607-Q-A-Argo-SRV
해당 뉴스의 제목 요약의 길이가 263로 측정됩니다.

하지만 지금 news, content 테이블의 excerpt 컬럼의 varchar의 길이는 `255` 입니다..!
따라서 뉴스를 저장할 수 없는 문제가 발생하므로 컬럼의 길이를 늘려야 할 것 같습니다.

적당하게 512로 설정할 지, 아예 `TEXT` 타입으로 바꿀지 고민이 드네요.
우선 512로 설정하고 추후 같은 문제가 발생 시 다른 타입으로 바꿔도 좋을 것 같습니다.

아직 서버가 세팅되지 않았으므로, `V1__init_news.sql` 파일을 수정해도 좋을 것 같습니다.

**Comment by Laeng** [comment]
이슈 관리와 미래의 인수 인계를 생각한다면 마음 편하게 TEXT 타입으로 바꾸는 것이 속 편할 것 같습니다.
어떻게 생각하시는지요?

**Comment by seokjin8678** [comment]
@Laeng 
https://medium.com/daangn/varchar-vs-text-230a718a22a1
MySQL에서 VARCHAR vs TEXT 타입을 비교한 내용이에요!
글의 마지막에 어떤 기준으로 선택해야 하는지 나와있는데, 데이터를 읽을 때 항상 컬럼이 필요한 경우 `VARCHAR`를 선택하라고 나와있네요!
`excerpt`의 경우, 항상 조회가 되는 컬럼이므로 TEXT 보다는 VARCHAR를 선택하는게 좋아 보입니다..!
아니면 news 테이블에 `excerpt` 컬럼이 꼭 필요한가? 라는 생각도 할 수 있을 것 같네요!

**Comment by Laeng** [comment]
`excerpt` 같은 경우 SSO를 위한 사이트맵 생성과 사용자에게 요약을 제공할때 사용하려고 했어요.
512 까지 늘리고 초과시 잘라야할 것 같아요

**Comment by seokjin8678** [comment]
별도의 컬럼으로 생성하거나, 또다른 테이블을 만들어서 해결할 수 있을 것 같네요!
