### ISSUE TITLE
feat: 외부 API 호출에서 Retrofit을 적용한다.

### ISSUE THREAD

**Issue by seokjin8678** [galaxyhub-korea/galaxyhub-backend#42]
## 이슈 내용

#36 에서 제안주신 내용입니다.

안드로이드에서 Retrofit을 사용하던데, 서버에서 사용해볼 생각을 못했네요. 😂
또한 스프링 부트 3.2 에서 `RestTemplate`를 대체하는 `RestClient`가 생겼는데 이와 비교해서 어떤 장점이 있는지 확인하면 좋을 것 같습니다.

**Comment by Laeng** [comment]
관련 사항을 저도 한번 찾아서 정리 해보도록 하겠습니다!

**Comment by Laeng** [comment]
Spring의 RestClient 의 경우 인터페이스 생성과 같은 특별한 절차 없이 빌더 패턴으로 가져와 바로 쓸 수 있는 장점이 있고,Restrofit2의 경우 인터페이스 생성과 같은 부수적인 절차가 있으나, 어노테이션을 통해 해당 요청이 POST, GET 과 같은 HTTP 요청 메서드를 한눈에 볼 수 있는 장점이 있습니다.

지금 도입한 RestClient 를 뛰어넘을 만큼 Retrofit2 만의 이점을 제가 찾지 못했고, RestClient도 충분히 편하니 유지합시다! 헤헤
